POST http://localhost:8080/book/save
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "isbn": "11",
  "price": 10,
  "description": "A Handbook of Agile Software Craftsmanship",
  "coverImage": "https://example.com/cleancode.jpg"
}

###
POST http://localhost:8080/book/save
Content-Type: application/json

{
  "title": "Paganin",
  "author": "Robert C. Martin",
  "isbn": "12",
  "price": 12.99,
  "description": "A Handbook of Agile Software Craftsmanship",
  "coverImage": "https://example.com/cleancode.jpg"
}

###
POST http://localhost:8080/book/save
Content-Type: application/json

{
  "title": "Dog",
  "author": "Robert C. Martin",
  "isbn": "13",
  "price": 19.99,
  "description": "A Handbook of Agile Software Craftsmanship",
  "coverImage": "https://example.com/cleancode.jpg"
}


###
GET http://localhost:8080/book/allBook?page=0&size=2&sort=title,asc HTTP/1.1
Host: localhost:8080
Accept: application/json

###
GET http://localhost:8080/book/getById?id=2
Host: localhost:8080
Accept: application/json


###
GET http://localhost:8080//book/betweenByprice?price1=11&price2=20
Accept: application/json